name: raintree
description: A new Flutter project.
version: 1.0.0+1
publish_to: none
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  dio: ^4.0.0
   # 屏幕适配
  flutter_screenutil: ^5.0.0
   # storage
  shared_preferences: ^2.0.6
   # google map
  google_maps_flutter: ^2.0.9
   # 滑动panel
  sliding_up_panel: ^2.0.0+1
   # 图片选择
  image_picker: 0.8.3+3
  # 日期
  intl: ^0.17.0
  # loading
  flutter_easyloading: ^3.0.3
  # 扫码
  qr_code_scanner: ^0.5.2
  # ID输入框
  flutter_verification_box: ^2.0.0
  loading_gifs: ^0.3.0
  # 列表动画
  flutter_staggered_animations: ^1.0.0
  # 定位
  location: ^4.3.0
  # 二维码
  qr_flutter: ^4.0.0
  # swiper
  card_swiper: ^1.0.4
  # call phone
  url_launcher: ^6.0.12
  # 滑动按钮
  flutter_slidable: ^0.6.0
  
  flutter: 
    sdk: flutter

dev_dependencies: 
  lints: 1.0.1
  dio_http_formatter: ^2.0.0
  flutter_test: 
    sdk: flutter
    
module:
    androidX: true

flutter: 
  uses-material-design: true
  assets:
    - images/

