name: swapapp
description: A new Flutter project.
version: 1.0.0+1
publish_to: none
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  dio: ^4.0.0
   # 屏幕适配
  flutter_screenutil: ^5.0.0
   # storage
  shared_preferences: ^2.0.6
   # google map
  google_maps_flutter: ^2.0.4
   # 滑动panel
  sliding_up_panel: ^2.0.0+1
  # toast
  fluttertoast: ^8.0.8
   # 图片选择
  image_picker: 0.8.3+3
  # 日期
  intl: ^0.17.0
  # loading
  flutter_easyloading: ^3.0.3
  
  flutter: 
    sdk: flutter

dev_dependencies: 
  lints: 1.0.1
  dio_http_formatter: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - images/

